### ISSUE TITLE
CalDAV support

### ISSUE THREAD

**Issue by emersion** [emersion/go-webdav#10]
This library needs a CalDAV client & server implementation.

https://tools.ietf.org/html/rfc4791

- [x] Client
- [ ] Server

**Comment by zhenzhaoya** [comment]
Do you have any plans to implement CalDAV Server?

**Comment by emersion** [comment]
Pull requests are welcome.

**Comment by zhenzhaoya** [comment]
Thank you very much. I pulled the code, but I can't use it yet. I'll study it.

**Comment by emersion** [comment]
Some WIP server work is sitting in https://github.com/emersion/go-webdav/compare/caldav-server

**Comment by emersion** [comment]
This work is now merged.
