### ISSUE TITLE
Need help in running caldav server

### ISSUE THREAD

**Issue by nikita-cerejo** [emersion/go-webdav#119]
Can anyone please help with how to run the caldav server? It would be of great help if anyone helps out.

**Comment by emersion** [comment]
This is not a CalDAV server. This is a library for building CalDAV servers.

**Comment by nikita-cerejo** [comment]
Yes thats what I am trying to do. I want to build a caldav server and I found your library but I don't know how to proceed. I mean how can I start with. I am able to run webdav server but after that how to go ahead to build caldav server, I don't know. Please can you help me with that?
