### ISSUE TITLE
About the format of the return path of method "ReadDir"

### ISSUE THREAD

**Issue by Elnus** [emersion/go-webdav#163]
![image](https://github.com/emersion/go-webdav/assets/95835763/fca1646d-64e0-49a0-be38-a7a9ae6034b2)

![image](https://github.com/emersion/go-webdav/assets/95835763/df3ad770-5a39-419d-ac2a-fbe84c58f140)

The code and results  is shown in the picture.

For the path returned by method ReadDir in Client and LocalFileSystem,i will get different path  forms from the root path and the subpath.Should we unify whether the path ends with the character "/"?

**Comment by emersion** [comment]
Not sure this makes sense. The client just returns whatever the server sent back.

**Comment by Elnus** [comment]
That's so confusing.When the `Client.ReadDir` passes in `/temp/`,it return `/temp/`.It seems that the return value and passed in are the same.And the sub path is not like this.I can't tell explicitly if it's a path or a file.

**Comment by emersion** [comment]
The only way to know whether an entry is a directory is to use the `IsDir()` method.

**Comment by Elnus** [comment]
Ok, thanks for the reply.
