### ISSUE TITLE
don't force fetching GetLastModified on AddressBook queries

### ISSUE THREAD

**Issue by AlmogBaku** [emersion/go-webdav#33]
I noticed that icloud doesn't add the GetLastModified property on `addressbook-multiget` and `addrssbook-query` calls, however `decodeAddressList()`[see code here](https://github.com/emersion/go-webdav/blob/master/carddav/client.go#L239) returns error when not exists.

**Comment by AlmogBaku** [comment]
@emersion

**Comment by emersion** [comment]
If the server returns 404 for this prop, go-webdav just ignores the error and doesn't set `LastModified`. So it should be fine.

What is the error returned by the server?

**Comment by AlmogBaku** [comment]
the server just doesn't return this value, and the code [in this line](https://github.com/emersion/go-webdav/blob/master/carddav/client.go#L239) just return an error.

I can do a PR

**Comment by emersion** [comment]
Ah. `DecodeProp` should probably generate a 404 if the property isn't returned at all then.

**Comment by AlmogBaku** [comment]
Trying to debug again... i'll get back to you w/ more details

**Comment by AlmogBaku** [comment]
The problem is that `DecodeProp` returns  `missingPropError` error which doesn't implement `HTTPError` therefore it cannot be ignored by `HTTPErrorFromError(err).Code == http.StatusNotFound`....

**Comment by AlmogBaku** [comment]
we need to change this line to:
```
if err := resp.DecodeProp(&getLastMod); err != nil && !internal.IsMissingProp(err) {
```
