### ISSUE TITLE
`internal.Response.Status` is not unmarshaled for client

### ISSUE THREAD

**Issue by AlmogBaku** [emersion/go-webdav#39]
`internal.Response.Status` is not being updated and stays nil. The information about the entry status is present in `internal.Response.Propstat[0].Status` instead

**Comment by emersion** [comment]
It seems to work properly. Added a test for it: https://github.com/emersion/go-webdav/commit/f4e3fe8c0aee8e6266f5a36ef77e6d67a4600578

**Comment by AlmogBaku** [comment]
the thing is the status should be a part of propstat! your test doesn't reflect the rfc

**Comment by emersion** [comment]
My test _comes from_ the RFC. See the link above `exampleDeleteMultistatusStr`.

There's no `<propstat>` element involved here.

**Comment by AlmogBaku** [comment]
interesting... here it's different:
https://tools.ietf.org/html/rfc4918#section-9.1.3

**Comment by emersion** [comment]
Bleh, it's actually this one: https://tools.ietf.org/html/rfc4918#section-9.6.2

**Comment by emersion** [comment]
Yes. It's different for a propstat to return an error status. It means the resource itself hasn't caused an error, but one or more props have.

Closing because go-webdav does the right thing.

**Comment by AlmogBaku** [comment]
thanks for the clarification.
