### ISSUE TITLE
internal: r/w roundtrip of Time broken

### ISSUE THREAD

**Issue by sbinet** [emersion/go-webdav#47]
hi,

trying to retrieve the list of contacts (served by `hydroxide`) I noticed the `internal.Time` value XML encoding/decoding roundtrip was broken:

- marshaling is done with `time.RFC1123Z`
- unmarshaling with `net/http.ParseTime` that only has: `[http.TimeFormat, time.RFC850, time.ANSIC]` as a list of possible time formats.

**Comment by emersion** [comment]
Ooops. I guess we should probably just use `http.TimeFormat`. Need to be careful about:

> The time being formatted must be in UTC for Format to generate the correct format.
