### ISSUE TITLE
Client configuration support

### ISSUE THREAD

**Issue by dmp42** [emersion/go-webdav#6]
Are you considering support for https://tools.ietf.org/html/rfc6352#section-9.3 ?

**Comment by emersion** [comment]
Yeah, that's a good idea.

**Comment by dmp42** [comment]
Getting familiar with your code... should I start poking around https://github.com/emersion/go-webdav/blob/master/prop.go#L103 ?

**Comment by dmp42** [comment]
No problem. I'll dig a bit into this and let you know if I come up with a workable PR. Reading the RFC for now - it's... special... :P

**Comment by emersion** [comment]
This has now been implemented.
