### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by grossamos** [emersion/go-webdav#95]
Hello, we've recently come across your project and are very interested in using it.
However despite the large count of contributors and people using this library we've failed to find any source of documentation.
Does your project have documentation? If yes, could this possibly be pointed to somehow?

**Comment by emersion** [comment]
Just like any other Go project, the docs are on https://pkg.go.dev/github.com/emersion/go-webdav

**Comment by grossamos** [comment]
Thank you ever so much for your feedback 👍
